/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Database;
import Model.Nasabah;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author faoezanf
 */
public class data_nasabah extends javax.swing.JFrame {
    
    public ArrayList<Nasabah> listNasabah = new ArrayList<>();
    
    public data_nasabah() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        noktp = new javax.swing.JTextField();
        nohp = new javax.swing.JTextField();
        saldo = new javax.swing.JTextField();
        sex = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbNasabah = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        nasabahAdded = new javax.swing.JLabel();
        noRekHapus = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        noHpEdit = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        labelEdit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NASABAH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 150, -1));
        getContentPane().add(noktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 150, -1));

        nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nohpActionPerformed(evt);
            }
        });
        getContentPane().add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 150, -1));

        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        getContentPane().add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 150, -1));

        sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);
            }
        });
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, 20));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Jenis Kelamin ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 25));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("No KTP          ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 90, 20));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("No HP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 40, 20));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Saldo Awal");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 70, 20));

        jButton2.setText("Tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        tbNasabah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Jenis Kelamin", "No. KTP", "No. HP", "Sisa Saldo", "No. Rekening"
            }
        ));
        jScrollPane1.setViewportView(tbNasabah);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 440, 110));

        jButton1.setText("<< Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 80, -1));

        nasabahAdded.setForeground(new java.awt.Color(153, 255, 153));
        nasabahAdded.setText("✓ Nasabah berhasil ditambah");
        getContentPane().add(nasabahAdded, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        noRekHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRekHapusActionPerformed(evt);
            }
        });
        getContentPane().add(noRekHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 140, -1));

        jLabel8.setForeground(new java.awt.Color(204, 0, 51));
        jLabel8.setText("Masukkan No. Rekening");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("untuk menghapus nasabah");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 140, -1));

        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("Pilih No. rekening");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 204, 0));
        jLabel11.setText("untuk update");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 90, -1));

        jLabel12.setForeground(new java.awt.Color(255, 204, 0));
        jLabel12.setText("Masukkan No. Hp");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 120, -1));

        noHpEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noHpEditActionPerformed(evt);
            }
        });
        getContentPane().add(noHpEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 110, -1));

        btnEdit.setText("Ubah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        labelEdit.setForeground(new java.awt.Color(153, 255, 0));
        labelEdit.setText("✓ No. Hp Nasabah berhasil diganti");
        getContentPane().add(labelEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("/Users/faoezanf/Documents/GUI/Nasabah-01.png")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nohpActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.nama.setText("");
        this.noktp.setText("");
        this.nohp.setText("");
        this.saldo.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new MenuAwal().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void noRekHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRekHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noRekHapusActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.noRekHapus.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void noHpEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noHpEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noHpEditActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        this.noHpEdit.setText("");
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEdit;
    private javax.swing.JTextField nama;
    private javax.swing.JLabel nasabahAdded;
    private javax.swing.JTextField noHpEdit;
    private javax.swing.JTextField noRekHapus;
    private javax.swing.JTextField nohp;
    private javax.swing.JTextField noktp;
    private javax.swing.JTextField saldo;
    private javax.swing.JComboBox<String> sex;
    private javax.swing.JTable tbNasabah;
    // End of variables declaration//GEN-END:variables

//    public void tesdoang () {
//        for (int i = 0; i < listNasabah.size(); i++) {
//            listNasabah.get(i).getNoRek();
//        }
//    }
    public void setDataNasabah(ArrayList<Nasabah> nasabah) {
        for (int j = 0; j < nasabah.size(); j++) {
            tbNasabah.setValueAt(nasabah.get(j).getNama(), j, 0);
            tbNasabah.setValueAt(nasabah.get(j).getSex(), j, 1);
            tbNasabah.setValueAt(nasabah.get(j).getNoKtp(), j, 2);
            tbNasabah.setValueAt(nasabah.get(j).getNoHp(), j, 3);
            tbNasabah.setValueAt(nasabah.get(j).getSaldo(), j, 4);
            tbNasabah.setValueAt(nasabah.get(j).getNoRek(), j, 5);
        }
    }
    
    public String nama() {
        return this.nama.getText();
    }
    
    public String sex() {
        return this.sex.getSelectedItem().toString();
    }
    
    public String noKtp() {
        return this.noktp.getText();
    }
    
    public String noHp() {
        return this.nohp.getText();
    }
    
    public double saldo() {
        Double d;
        d = Double.parseDouble(this.saldo.getText());
        return d;
    }
    
    public String noRek() {
        return this.noKtp();
    }
    
    public String noRekHapus() {
        return this.noRekHapus.getText();
    }
    
    public String noRekEdit() {
        return this.jComboBox1.getSelectedItem().toString();
    }
    
    public String noHpEdit() {
        return this.noHpEdit.getText();
    }
    
    public JButton btnAdd() {
        return this.jButton2;
    }
    
    public JButton btnDel() {
        return this.jButton3;
    }
    
    public JButton btnEdit() {
        return this.btnEdit;
    }
    
    public void nasabahTertambah() {
        this.nasabahAdded.setVisible(true);
    }
    
    public void nasabahBelumTertambah() {
        this.nasabahAdded.setVisible(false);
    }
    
    public void editBerhasil() {
        this.labelEdit.setVisible(true);
    }
    
    public void editBelumBerhasil() {
        this.labelEdit.setVisible(false);
    }
    
    public void addActionListener(ActionListener e) {
        this.jButton2.addActionListener(e);
    }
    
    public void addActionListener2(ActionListener e) {
        this.jButton3.addActionListener(e);
    }
    
    public void addActionListener3(ActionListener e) {
        this.btnEdit.addActionListener(e);
    }
    
    public void setValueEdit() {
        try {
            Database db = new Database();
            ResultSet rs = db.getData("select noRek from nasabah");
            jComboBox1.removeAllItems();
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("noRek"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
}
