package View;

import Model.Database;
import Model.Pemasukan;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class dataPemasukan extends javax.swing.JFrame {

    public ArrayList<Pemasukan> listPemasukan = new ArrayList<>();
    
    public dataPemasukan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPemasukan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jmlPemasukan = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        tanggalPemasukan = new javax.swing.JTextField();
        noRek = new javax.swing.JComboBox<>();
        btnHapus = new javax.swing.JButton();
        data = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PEMASUKAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jButton1.setText("<< Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbPemasukan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No. Rekening", "Jumlah Uang", "Tanggal Pemasukan"
            }
        ));
        jScrollPane1.setViewportView(tbPemasukan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 370, 130));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Rekening");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 80, 20));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah Uang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, 25));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Pemasukan     ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 140, 20));

        jmlPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlPemasukanActionPerformed(evt);
            }
        });
        getContentPane().add(jmlPemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 150, -1));

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));
        getContentPane().add(tanggalPemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 150, -1));

        noRek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noRekActionPerformed(evt);
            }
        });
        getContentPane().add(noRek, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 150, -1));

        btnHapus.setText("Hapus Semua");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        data.setForeground(new java.awt.Color(204, 255, 0));
        data.setText("✓ Data berhasil tersimpan");
        getContentPane().add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("/Users/faoezanf/Documents/GUI/Pemasukan.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new lakukanTransaksi().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        this.jmlPemasukan.setText("");
        this.tanggalPemasukan.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void noRekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noRekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noRekActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jmlPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlPemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlPemasukanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel data;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlPemasukan;
    private javax.swing.JComboBox<String> noRek;
    private javax.swing.JTextField tanggalPemasukan;
    private javax.swing.JTable tbPemasukan;
    // End of variables declaration//GEN-END:variables
    public void setDataPemasukan(ArrayList<Pemasukan> Pemasukan){
        for (int j = 0; j < Pemasukan.size(); j++) {
            tbPemasukan.setValueAt(Pemasukan.get(j).getNoRekPemasukan(), j, 0);
            tbPemasukan.setValueAt(Pemasukan.get(j).getJumlahPemasukan(), j, 1);
            tbPemasukan.setValueAt(Pemasukan.get(j).getTanggalPemasukan(), j, 2);
        }
    }
    
    public String noRek() {
        return this.noRek.getSelectedItem().toString();
    }
    
    public double jmlUang() {
        Double d;
        d = Double.parseDouble(this.jmlPemasukan.getText());
        return d;
    }
    
    public String tgl() {
        return this.tanggalPemasukan.getText();
    }
    
    public JButton btnAdd() {
        return this.btnAdd;
    }

    public JButton btnHapus() {
        return this.btnHapus;
    }
    
    public void addActionListener(ActionListener e) {
        this.btnAdd.addActionListener(e);
    }
    
    public void addActionListener2(ActionListener e) {
        this.btnHapus.addActionListener(e);
    }
    
    public void setValueEdit() {
        try {
            Database db = new Database();
            ResultSet rs = db.getData("select noRek from nasabah");
            noRek.removeAllItems();
            while (rs.next()) {
                noRek.addItem(rs.getString("noRek"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void dataBelum () {
        this.data.setVisible(false);
    }
    
    public void dataMasuk() {
        this.data.setVisible(true);
    }
}
