package View;

import Model.Database;
import Model.Penarikan;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class dataPenarikan extends javax.swing.JFrame {

    public ArrayList<Penarikan> listPenarikan = new ArrayList<>();

    public dataPenarikan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPenarikan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jml = new javax.swing.JTextField();
        tgl = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        noRek = new javax.swing.JComboBox<>();
        data = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PENARIKAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 50));

        tbPenarikan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No. Rekening", "Jumlah Uang", "Tanggal Penarikan"
            }
        ));
        jScrollPane1.setViewportView(tbPenarikan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 370, 130));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Rekening");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 80, 20));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jumlah Uang");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, 25));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tanggal Penarikan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 110, 20));

        jml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlActionPerformed(evt);
            }
        });
        getContentPane().add(jml, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 150, -1));

        tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglActionPerformed(evt);
            }
        });
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 150, -1));

        btnAdd.setText("Tambah");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jButton1.setText("<< Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, -1, -1));

        getContentPane().add(noRek, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 150, -1));

        data.setForeground(new java.awt.Color(204, 255, 0));
        data.setText("✓ Data berhasil ditambah");
        getContentPane().add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        btnHapus.setText("Hapus Semua");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/faoezanf/Documents/GUI/Penarikan.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        this.jml.setText("");
        this.tgl.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new lakukanTransaksi().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel data;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jml;
    private javax.swing.JComboBox<String> noRek;
    private javax.swing.JTable tbPenarikan;
    private javax.swing.JTextField tgl;
    // End of variables declaration//GEN-END:variables
    public void setDataPenarikan(ArrayList<Penarikan> penarikan) {
        for (int j = 0; j < penarikan.size(); j++) {
            tbPenarikan.setValueAt(penarikan.get(j).getNoRekPenarikan(), j, 0);
            tbPenarikan.setValueAt(penarikan.get(j).getJumlahPenarikan(), j, 1);
            tbPenarikan.setValueAt(penarikan.get(j).getTanggalPenarikan(), j, 2);
        }
    }

    public String noRek() {
        return this.noRek.getSelectedItem().toString();
    }

    public double jmlUang() {
        Double d;
        d = Double.parseDouble(this.jml.getText());
        return d;
    }

    public String tgl() {
        return this.tgl.getText();
    }

    public JButton btnAdd() {
        return this.btnAdd;
    }

    public JButton btnHapus() {
        return this.btnHapus;
    }
    
    public void addActionListener(ActionListener e) {
        this.btnAdd.addActionListener(e);
    }
    
    public void addActionListener2(ActionListener e) {
        this.btnHapus.addActionListener(e);
    }
    
    public void setValueEdit() {
        try {
            Database db = new Database();
            ResultSet rs = db.getData("select noRek from nasabah");
            noRek.removeAllItems();
            while (rs.next()) {
                noRek.addItem(rs.getString("noRek"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void dataBelum () {
        this.data.setVisible(false);
    }
    
    public void dataMasuk() {
        this.data.setVisible(true);
    }
}
