/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import Model.Database;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author faoezanf
 */
public class NasabahE extends javax.swing.JFrame {

    /**
     * Creates new form NasabahE
     */
    public NasabahE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        noHpEdit = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(248, 255, 247));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Edit Data Nasabah");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(140, 110, 330, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel4.setText("Masukkan No. HP yang baru :");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(140, 300, 390, 30);

        jPanel1.setBackground(new java.awt.Color(129, 204, 186));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(121, 187, 171));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel5.setText("Nasabah");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(40, 20, 120, 33);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(180, 0, 180, 80);

        jLabel2.setText("Welcome, user!");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(820, 10, 220, 15);

        jButton5.setForeground(new java.awt.Color(255, 0, 0));
        jButton5.setText("Log Out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(820, 30, 110, 30);

        btnTransaksi.setBackground(new java.awt.Color(129, 204, 186));
        btnTransaksi.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        btnTransaksi.setText("Transaksi");
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btnTransaksi);
        btnTransaksi.setBounds(380, 20, 150, 43);

        btnHome.setBackground(new java.awt.Color(129, 204, 186));
        btnHome.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome);
        btnHome.setBounds(10, 20, 150, 43);

        jPanel4.add(jPanel1);
        jPanel1.setBounds(0, 0, 1001, 80);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(530, 210, 280, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 28)); // NOI18N
        jLabel6.setText("Pilih No. Rekening untuk diedit :");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(140, 210, 390, 30);

        noHpEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noHpEditActionPerformed(evt);
            }
        });
        jPanel4.add(noHpEdit);
        noHpEdit.setBounds(530, 300, 280, 40);

        btnEdit.setBackground(new java.awt.Color(129, 204, 186));
        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnEdit.setText("Ubah");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel4.add(btnEdit);
        btnEdit.setBounds(380, 400, 190, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        this.setVisible(false);
        new MainControllerUtama();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        this.setVisible(false);
        new MainControllerTransaksi1();
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void noHpEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noHpEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noHpEditActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField noHpEdit;
    // End of variables declaration//GEN-END:variables

    public void setValueEdit() {
        try {
            Database db = new Database();
            ResultSet rs = db.getData("select noRek from nasabah");
            jComboBox1.removeAllItems();
            while (rs.next()) {
                jComboBox1.addItem(rs.getString("noRek"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void addActionListener3(ActionListener e) {
        this.btnEdit.addActionListener(e);
    }

    public JButton getBtnHome() {
        return btnHome;
    }

    public JButton getBtnTransaksi() {
        return btnTransaksi;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }
    
    public String noRekEdit() {
        return this.jComboBox1.getSelectedItem().toString();
    }
    
    public String noHpEdit() {
        return this.noHpEdit.getText();
    }
}
